# Generated by Django 2.2.2 on 2019-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190604_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='biz_pics'),
        ),
    ]
