# Generated by Django 2.2.2 on 2019-06-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business',
            new_name='hood',
        ),
    ]
